### ISSUE TITLE
Add error message in exception when connection failed

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#11]
When connection error occurs, we only have a exception with `Unable to connect to 4D Server`. There is an error message in the C library. It can be usefull to change
 https://github.com/ibrewster/p4d/blob/50b2bc71a55971f953fe15b1c8a2a63821ed4159/p4d/p4d.py#L650

to:

```python
raise OperationalError("Unable to connect to 4D Server: {0}".format(ffi.string(self.connptr.error_string)))
```

**Comment by ibrewster** [comment]
Agreed. Change made.
