### ISSUE TITLE
Error "Failed to execute statement" on SELECT without more information

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#12]
I'm have a 4D table "Societe" with 66 columns. When reading data, I can SELECT all column except "OB_GestionDossAbsence". When I include this column un SELECT, this error occurs:
```
...
  File "/volumes/users/olivier/dev/scopuli/scopuli-cli/venv3/lib/python3.6/site-packages/p4d/p4d.py", line 382, in execute
    raise ProgrammingError(ffi.string(self.lib4d_sql.fourd_error(self.fourdconn)))
p4d.p4d.ProgrammingError: b'Failed to execute statement.'
```

The data type of this column is 21.

How can I have more info on this error?

**Comment by ibrewster** [comment]
Unfortunately that's as much information as the underlying C library/ 4D returns about the error. I have found it quite annoying many, many times. Do make sure you are running the latest version of p4d, as older versions had a bug that would cut off the statement and/or response if it got too long, and of course double-check your spelling, that your select statement exactly matches the columns in the database. Other than that, the only thing I can suggest is to try running the SQL directly in 4D if you can, and see if that tells you anything. 

For what it's worth, "Failed to execute statement" means that 4D didn't like something about the query it received, as opposed to, say, a failure to parse the result or the like. Sorry for not being of more help!

**Comment by ibrewster** [comment]
Ah, gotcha. In the C library that I have access to (which is from 2009, and has not been updated by the 4D team since) there are only 12 data types, including unknown:

```
typedef enum
{
	VK_UNKNOW=0,
	VK_BOOLEAN,
	VK_BYTE,
	VK_WORD,
	VK_LONG,
	VK_LONG8,
	VK_REAL,
	VK_FLOAT,
	VK_TIMESTAMP,
	VK_DURATION,
	VK_STRING,
	VK_BLOB,
	VK_IMAGE 
}FOURD_TYPE;
```

So yeah, any "new" data types 13 or higher would be lumped into "unknown" - I'd have to look more closely, but I suspect they'd just be treated as strings, which may or may not work for any given type. If I had a list of the "new" types and corresponding numbers, I might be able to work up something, but definite emphasis on the MIGHT. Sorry!

**Comment by olivier-monaco** [comment]
Ho yes, I saw and used this list some months ago but unable to find it again. Great. Problem occurs only when selecting columns with data type 21.

To help debugging I wrote a very simple query tool: https://github.com/olivier-monaco/p4dcli

It works like the "mysql" tool.

So I have the following data type in the 4D database:
```
+-----------+
| DATA_TYPE |
+-----------+
| 1         |
| 3         |
| 4         |
| 6         |
| 8         |
| 9         |
| 10        |
| 12        |
| 13        |
| 14        |
| 18        |
| 21        |
+-----------+
```

(Query : `SELECT DISTINCT DATA_TYPE FROM _USER_COLUMNS;`)

I will try to guess type over 12...

**Comment by olivier-monaco** [comment]
Type 13 is always used for columns named "UUID" and have a length of 16. It seems to be the binary representation of a UUID.

Type 14 : I have no data in tables with a colum of this data type.

Type 18 : I contents some binary data that looks like various 4D data format (4D Text...)

Type 21 : I can't use SELECT on it.

**Comment by olivier-monaco** [comment]
About error, we can have a better error message using:
```python
self.lib4d_sql.fourd_errno(self.fourdconn)
```

This give a SQL error code and the following page give message of each code: http://doc.4d.com/4Dv17/4D/17/Appendix-A-SQL-Error-Codes.300-3786765.en.html

It maybe be usefull to raise more helpfull errors.

And so, when I select a 21-type column the error is 1203 (The functionality is not implemented.).

We can't do anything about that ;).

**Comment by ibrewster** [comment]
As you can see from your original post, I already have that code there:

`raise ProgrammingError(ffi.string(self.lib4d_sql.fourd_error(self.fourdconn)))`

**Comment by olivier-monaco** [comment]
Not `fourd_error` but `fourd_errno`. See the last 2 chars. This give the error number.

**Comment by ibrewster** [comment]
Ah, missed that. I'll have to look into it when I have a chance.

**Comment by ibrewster** [comment]
I'm thinking type 21 might be an object field. According to this page:

http://doc.4d.com/4Dv17/4D/17/4D-field-types.300-3743587.en.html

Object is the only field type that we don't handle and then according to this page:

http://doc.4d.com/4Dv15/4D/15/Object-Field-data-type.300-2018651.en.html

"The following 4D features or commands to not support Object fields", with SQL SELECT, INSERT and UPDATE being listed there under "No Support". So as you said, I think we're just flat out-of-luck with those.

As far as the type "integers" go, I'm not sure the integer representations are used anywhere in the code (and I'm not sure where you are getting them from). Tracing the request/response through the C code, I'm seeing the response header containing the field types as strings like VK_STRING or whatever, that match up to the entries in the enum. So at no point that I can find is there a field type "13" or the like. Note that 4D has any number of data types that don't correspond to field types - Array, for example. Feel free to point out if I've missed something! :)

**Comment by olivier-monaco** [comment]
About type 21, you're right, it's an object field.

This integer representation of types are in _USER_COLUMNS table, column DATA_TYPE, which list columns of tables. I use this system table to discover columns (and _USER_TABLES to discover tables).
