### ISSUE TITLE
Base64 encoding error for characters code > 128

### ISSUE THREAD

**Issue by guillaumes75** [ibrewster/p4d#13]
Hello,
I'm a happy user of p4d, and would like to thank you a lot for this very useful library. I use it quite often !

I noticed an bug when sending a request containing accented characters.
The requests always fail with error "_Failed to parse statement_."

Here is an example of the query failing with the above error:

```SQL
select count(*) from people where first_name = 'René';
```

At first I thought it was an issue on 4D side so I tried to work around it.
But after much digging I found it was an issue in p4d.
This is happening in base64.c, in function `base64_encode`.
```c
unsigned char *base64_encode(const char *str, size_t length, int *ret_length)
{
	const char *current = str;
	unsigned char *p;
	unsigned char *result;

	if (((length + 2) / 3) >= (1 << (sizeof(int) * 8 - 2))) {
		if (ret_length != NULL) {
			*ret_length = 0;
		}
		return NULL;
	}

	result = (unsigned char *)malloc(((length + 2) / 3) * 4* sizeof(char)+1);
	p = result;

	while (length > 2) { /* keep going until we have less than 24 bits */
		*p++ = base64_table[current[0] >> 2];                         // <-- BUG HERE !
	// ...snip...
```

The last line shown has the bug: 
if `current[0]` is >=128, it is considered negative because it has the type `char`. 
When a negative number is shifted to the right, the most significant bit of the number are set to 1 to preserve the sign. In that case, the computed index is incorrect. 
This case does not happen for regular ASCII chars because they have values < 128 but it systematically happens with non ASCII chars.
To fix it, simply declare the variable `current` as an unsigned char pointer, so it will never be considered negative.
Here is the proposed fix:
```diff 
unsigned char *base64_encode(const char *str, size_t length, int *ret_length)
{
-	const char *current = str;
+	const unsigned char*current = (const unsigned char*)str;
	unsigned char *p;
	unsigned char *result;
```
Strangely enough, the original library 4d/SQLlib_4D has the correct type for `current`...
Would it be possible to issue a new release of p4d with this fix ?

Have a nice day !
-Guillaume

**Comment by ibrewster** [comment]
I went ahead and implemented the change you suggested. Note that I have not tested this at all, since I no longer have access to a 4D database.

Regarding the original library having the correct type for current, that's not really surprising - they've probably updated it several times since I last pulled the copy for this library. If I still had access to 4D, I could look at updating that, but as it is, this is essentially a dead project to me. Sorry!

**Comment by ibrewster** [comment]
Ok, so I just looked at the 4d/SQLlib_4D repository, and it looks like it hasn't been updated in 13 years! So yeah, I now have no idea why it is different... :P

**Comment by guillaumes75** [comment]
Why is it different ?   
Uh, it *could* be that the code in 4d/SQLlib_4D repo compiled with a warning because there is no explicit cast from `unsigned char *` to `char*` . Because of the warning, it is easy to believe the implicit conversion to `unsigned char *` is an error. Then it becomes tempting to revert to `char*` to "fix" the warning instead of adding an explicit cast.
Well, that's my little theory anyway.... :smile: 

Anyway, thanks a lot for this fix !
Indeed this is so nice of you to update this old project !
But I assure you this lib is still useful ! Well it is to me at least. :smile: 
Is there any chance this gets a release on PyPI ? :sweat_smile: 

-Guillaume

**Comment by ibrewster** [comment]
> Uh, it _could_ be that the code in 4d/SQLlib_4D repo compiled with a warning because there is no explicit cast from `unsigned char *` to `char*` . Because of the warning, it is easy to believe the implicit conversion to `unsigned char *` is an error. Then it becomes tempting to revert to `char*` to "fix" the warning instead of adding an explicit cast.
> Well, that's my little theory anyway.... 😄

Good theory! That sounds like something I would have done... 😄

> Is there any chance this gets a release on PyPI ? 😅

Oh, right - forgot about that! I'll try to get to that this weekend, or early next week. Might have to bug me a few more times before it happens though! 😄

**Comment by ibrewster** [comment]
Ummm...I think I still need to take care of this? Sorry about the delay!

**Comment by ibrewster** [comment]
The new version should now be uploaded to PyPi. Let me know if you get a chance to try it out.

**Comment by guillaumes75** [comment]
Niiice !
I installed it from PyPi and it seems to work great !
Thank you very much for this release !
:+1:
