### ISSUE TITLE
Error "double free or corruption" when closing cursor

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#3]
Hi,

Here is a snippet to show the problem:
```python
cnx = p4d.py4d_connection(...)
sql = 'SELECT * FROM _USER_TABLES;'
cur = cnx.cursor()
cur.execute(sql)
cur.close()
```

Running this code results in core dump with message "double free or corruption". The double free comes from the close function of py4d_cursor, ligne 218:
```python
        if self.result is not None:
            self.lib4d_sql.fourd_free_result(self.result)
        self.connection.close()
```

If the cursor have some results, we free it be don't set the result field to None. The close method of the connection will try to free it again. This will fix the problem:
```python
        if self.result is not None:
            self.lib4d_sql.fourd_free_result(self.result)
            self.result = None
        self.connection.close()
```
Regards,

Olivier

**Comment by ibrewster** [comment]
Thanks for the feedback. Technically, the check in `py4d_connection.close` is:

`if cursor.result is not None and cursor.result != ffi.NULL:`

and the call to `fourd_free_result(self.result)` *should* set `self.result` to NULL, so the check for `cursor.result != ffi.NULL` *should* prevent a double free situation.

That said, explicitly setting it to None on the python side as you've suggested certainly can't hurt, and would be a nice safety measure.
