### ISSUE TITLE
Closing a cursor close the connection

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#4]
Hi,

Here is a use case:
```
    sql = 'SELECT * FROM _USER_TABLES;'
    with closing(cnx4d.cursor()) as cur:
        cur.execute(sql)
        rows = cur.fetchall()
        print(len(rows))

    with closing(cnx4d.cursor()) as cur:
        cur.execute(sql)
        rows = cur.fetchall()
        print(len(rows))
```

The first cursor is okay. When running the query with the second cursor:
```
InternalError: Database not connected
```

**Comment by olivier-monaco** [comment]
Comes from https://github.com/ibrewster/p4d/blob/master/p4d/p4d.py#L220

Why closing the connection when the cursor is closed?

Removing this line fix the error. It also fix another error: using nested cursor like below generate a "double free" error.
```
    sql = 'SELECT * FROM _USER_TABLES;'
    with closing(cnx4d.cursor()) as cur:
        cur.execute(sql)
        rows = cur.fetchall()
        print(len(rows))

        with closing(cnx4d.cursor()) as cur2:
            cur2.execute(sql)
            rows = cur2.fetchall()
            print(len(rows))
```

**Comment by ibrewster** [comment]
When writing the interface, I was under the impression that calling close on the cursor should have the same result as calling close on the connection - i.e., that close is close connection, and close on the cursor is just a shortcut for those times when the cursor is readily available, but the connection is not (perhaps opened in a different thread or something). 

Looking back at the API specs, however, I see that this is not necessarily the case - the specs only talk about closing a cursor and throwing an error if attempting to reuse *that* cursor - not closing the connection as a whole. As such, I'll go ahead and change this behavior to just clear out the results and invalidate the cursor, but not close the connection.

**Comment by ibrewster** [comment]
Close connection command removed in commit https://github.com/ibrewster/p4d/commit/727825260bff839dd7606c4707f29737a9820660 API should behave closer to the standard expected behavior now
